btc:
  url: https://chain.api.btc.com/v3/
  coinDecimal: 0

eth:
  url:
  coinDecimal: 0

bitcny:
  url: http://185.208.208.184:5000
#  url: https://explorer.bitshares-kibana.info
  coinDecimal: 0

eos:
  url: 1
  coinDecimal: 0

trx:
  url: https://apilist.tronscan.org/api/
  coinDecimal: 0

server:
  url: http://127.0.0.1:6567/api/submit

